### ISSUE TITLE
actividad-5-cuadro comparativo-hernandez matra jorge luis

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-JORGELUIS2266#2]
[TIPOS DE TEXTO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-JORGELUIS2266/files/9716905/TIPOS.DE.TEXTO.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by Daisy-GonzalezLita12** [comment]
15 de 20

**Comment by josealfredo79** [comment]
@Daisy-GonzalezLita12 Favor de calificar objetivamente

**Comment by josealfredo79** [comment]
Calificación 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
